const Roles = {
  FULLTIME: "FULLTIME",
  DIRECTOR: "DIRECTOR",
  //Facility Roles
  FM_DEPUTY_HEAD: "DEPUTY_HEAD",
  FM_FACILITY_TEAM_LEAD: "FACILITY_TEAM_LEAD",
  FM_ADMIN_LEAD: "ADMIN_LEAD",
  ACCOUNTANT_LEAD: "ACCOUNTANT_LEAD",
};

export default Roles;
